### PR TITLE
Finished get, post, and delete API Routes [CB-1]

### PR DESCRIPTION
**Pull request by NathanP9000**
* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
This PR introduces three functional routes.

* **What is the current behavior? What does the code do before you made the new changes?** 
There is not current behavior.

* **What is the new behavior?**
We are able to get, delete, and add people to the Heroku app.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No breaking changes have been added.

* **Other information**:

### CODE REVIEW

**Review by iakujobi — COMMENTED** [review]
Your code is good. Just some changes needed:

- Remove either line 4 or 6. They are the same
- Change regular functions to arrow functions

**Review by iakujobi — DISMISSED** [review]
Good job! Ready to be merged

**Comment by Luis-ATapia** [comment]
Code looks great, well done!

**Review by Luis-ATapia — DISMISSED** [review]

**Comment by NathanP9000** [comment]
Thanks guys!

**Review by Codubee — APPROVED** [review]
LGTM!

**Review by Luis-ATapia — APPROVED** [review]

**Pull request merged**
