### PR TITLE
Yelp Routes MB-20,21,22

### PR DESCRIPTION
**Pull request by iakujobi**
* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
This PR introduces 3 get routes to the Yelp API. 

* **What is the current behavior? What does the code do before you made the new changes?** 
The current routes can now connect to the Yelp API as well as connect to the java-sample-api

* **What is the new behavior?**
3 new Get routes were created to connect, search, and get details of a business/event from the Yelp API

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Users will need to update their index.js file as well as update their package.json file to include some libraries

* **Other information**:

### CODE REVIEW

**Comment by NathanP9000** [comment]
Everything looks good

**Review by NathanP9000 — DISMISSED** [review]
Looks good

**Review by Luis-ATapia — CHANGES_REQUESTED** [review]
Functionality looks great! However, the console statements don't seem to be necessary so removing them would make your code look cleaner.

**Review by Luis-ATapia — DISMISSED** [review]
Code looks great now!

**Review by keziaabraham — DISMISSED** [review]
Your code looks good Ike! The only change I would suggest is taking out line 91 in the index.js file as it's not really needed, otherwise wonderful job!

**Review by keziaabraham — APPROVED** [review]
Good job Ike!

**Review by Luis-ATapia — APPROVED** [review]
Looks good Ike, great job.

**Pull request merged**
