### PR TITLE
Completed Routes for API (Get, Post and Delete): CB-1

### PR DESCRIPTION
**Pull request by sanjanajadhavv**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Introduces 3 routes to make api calls that can get, post or delete.

* **What is the current behavior?What does the code do before you made the new changes?** 
The code had errors in the delete route.

* **What is the new behavior?**
The new changes include 3 routes that allow users to be added or deleted, and also display the users in the database.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Users will need to install Axios and Express to run this application.

* **Other information**:
n/a

### CODE REVIEW

**Review by iakujobi — COMMENTED** [review]
Your code is good, but there are some minor errors.

- Modify regular function to arrow functions on lines 8, 15, 21, 28, 34, 40, 47, 54 and 60
- Remove the console.log on lines 9, 30, and 48 to make your code cleaner

**Review by keziaabraham — CHANGES_REQUESTED** [review]
Your code is clean and well written Sanjana! I agree with Ike, using the arrows makes the code easier to read and more efficient.

**Review by iakujobi — APPROVED** [review]
Good job! Code is ready to be merged

**Review by keziaabraham — APPROVED** [review]
Good job Sanjana!

**Pull request merged**
