### PR TITLE
Route to get stock from db MB-19

### PR DESCRIPTION
**Pull request by Luis-ATapia**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
This route gets various information from a stock in the database.

* **What is the current behavior? What does the code do before you made the new changes?** 
There is no current behavior as this is the first commit.

* **What is the new behavior?**
The new behavior introduces the ability to get a stocks information from the database using the route path call.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?
Users will be able to use this route to get the information of some stock in a database of stocks.

* **Other information**:

### CODE REVIEW

**Review by iakujobi — DISMISSED** [review]
Good job!

**Review by keziaabraham — CHANGES_REQUESTED** [review]
Good code Luis! You can remove lines 5 and 19 as it just extra space. Otherwise great code!

**Review by keziaabraham — CHANGES_REQUESTED** [review]
Hey I believe line 14 should be status 500 rather than 200.

**Review by keziaabraham — DISMISSED** [review]
Great job Luis!

**Review by iakujobi — DISMISSED** [review]
All good!

**Comment by sanjanajadhavv** [comment]
Your code looks good! Great job!

**Review by sanjanajadhavv — APPROVED** [review]
Your code looks good! Great job!

**Review by NathanP9000 — APPROVED** [review]
Looks good

**Pull request merged**
