### PR TITLE
Completed routes for api calls CB-1

### PR DESCRIPTION
**Pull request by Luis-ATapia**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Introduces three route paths that make API calls.

* **What is the current behavior? What does the code do before you made the new changes?** 
The code functions properly with no bugs and implements three route paths.

* **What is the new behavior?**
The code implements three route paths that make API calls to get all users in database or add/delete users.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Allows users to get all users in a database, add new users to the database, or delete a particular user from the database.

* **Other information**:

### CODE REVIEW

**Review by iakujobi — CHANGES_REQUESTED** [review]
Remove the body parameters on lines 32 & 52 in the get and delete routes. Body should only be used in the post route

**Review by iakujobi — DISMISSED** [review]
Looks good! Ready to be merged

**Review by NathanP9000 — DISMISSED** [review]
The code is very organized, and it looks functional!  I would remove the comments on lines 17, 28, and 43-45 to make the code look a little cleaner.

**Review by iakujobi — APPROVED** [review]
Code is ready to be merged!

**Review by NathanP9000 — APPROVED** [review]
Code looks good now

**Pull request merged**
