### PR TITLE
Routes completed for API calls CB-1

### PR DESCRIPTION
**Pull request by iakujobi**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Introduced three routes that make API calls

* **What is the current behavior? What does the code do before you made the new changes?** 
A new folder was created with my initials. The code did not have a folder containing the new index.js file

* **What is the new behavior?**
The code implements 3 routes paths that make API calls to add, delete users and get all users

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Users will need to update their package.json file to account for the installation of axios and express

* **Other information**:

### CODE REVIEW

**Review by NathanP9000 — DISMISSED** [review]
Code looks functional and organized! One thing I would do is remove the console.logs on lines 10 and 31 as those functions do not require the body part of the request, but that might just be me being picky.

**Comment by Luis-ATapia** [comment]
I agree with Nathan, removing the comments would clean up the code, but completely optional. Otherwise, your code appears to function as intended.

**Review by Luis-ATapia — DISMISSED** [review]

**Review by NathanP9000 — APPROVED** [review]
Code looks good now

**Comment by keziaabraham** [comment]
Good code Ike!

**Review by keziaabraham — APPROVED** [review]
Good code Ike!

**Pull request merged**
